# Generated by Django 5.2.1 on 2025-05-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='image_filter_choices',
        ),
    ]
