# Generated by Django 5.2.1 on 2025-05-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_commentartwork_commenttutorial_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commenttutorial',
            old_name='artwork',
            new_name='tutorial',
        ),
    ]
