# Generated by Django 5.2.1 on 2025-05-29 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_remove_artwork_image_filter_choices'),
        ('likes', '0002_likeartwork_liketutorial_delete_like'),
        ('tutorials', '0002_alter_tutorial_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liketutorial',
            options={},
        ),
        migrations.RenameField(
            model_name='liketutorial',
            old_name='content',
            new_name='tutorial',
        ),
        migrations.AlterUniqueTogether(
            name='likeartwork',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='liketutorial',
            unique_together={('owner', 'tutorial')},
        ),
        migrations.AlterField(
            model_name='likeartwork',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_likes', to='artworks.artwork'),
        ),
        migrations.RemoveField(
            model_name='likeartwork',
            name='content',
        ),
        migrations.RemoveField(
            model_name='liketutorial',
            name='artwork',
        ),
    ]
