# Generated by Django 5.2.1 on 2025-06-01 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutorial_title', models.CharField(max_length=255)),
                ('tutorial_description', models.TextField(blank=True)),
                ('preview_art', models.ImageField(blank=True, default='../default_post_rgq6aq', upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TutorialAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('reflection_text', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_attempt_owner', to=settings.AUTH_USER_MODEL)),
                ('tutorial_tried', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_tried', to='tutorials.tutorial')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TutorialFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor_feedback', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_owner', to=settings.AUTH_USER_MODEL)),
                ('tutorial_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='tutorials.tutorialattempts')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TutorialSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_number', models.PositiveIntegerField()),
                ('step_title', models.CharField(max_length=255)),
                ('step_content', models.TextField(blank=True)),
                ('step_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_steps_owner', to=settings.AUTH_USER_MODEL)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_steps', to='tutorials.tutorial')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
