# Generated by Django 5.2.1 on 2025-05-31 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_tutorialattempts_tutorialfeedback_tutorialsteps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialattempts',
            old_name='description',
            new_name='reflection_text',
        ),
        migrations.RenameField(
            model_name='tutorialattempts',
            old_name='image',
            new_name='submission_image',
        ),
        migrations.RenameField(
            model_name='tutorialfeedback',
            old_name='feedback',
            new_name='mentor_feedback',
        ),
    ]
