# Generated by Django 5.2.1 on 2025-06-01 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_rename_description_tutorialattempts_reflection_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialattempts',
            old_name='tutorial_try',
            new_name='tutorial_tried',
        ),
        migrations.RemoveField(
            model_name='tutorialattempts',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tutorialfeedback',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tutorialsteps',
            name='owner',
        ),
        migrations.AlterField(
            model_name='tutorialfeedback',
            name='tutorial_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='tutorials.tutorialattempts'),
        ),
    ]
